[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.0"
ci = "github"
installers = ["shell", "powershell"]
windows-archive = ".zip"
unix-archive = ".tar.gz"
create-release = true
dispatch-releases = true
github-release = "announce"
install-path = "~/.local/bin"
pr-run-mode = "skip"
build-local-artifacts = true
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
