networks:
  otlp:

volumes:
  tempo-data:

services:
  # Traces
  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    ports:
      - "4318:4318"
      - "3200:3200"
    volumes:
      - tempo-data:/var/tempo
      - ./tempo.yml:/etc/tempo.yaml
    depends_on:
      - memcached
    networks:
      - otlp
  memcached:
    image: memcached:1.6.38
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m # Set the maximum memory usage
      - MEMCACHED_THREADS=4 # Number of threads to use
    networks:
      - otlp

  # UI
  grafana:
    image: grafana/grafana:12.1.3
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - otlp
