[package]
name = "pctx_code_mode"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
# local
pctx_config = { path = "../pctx_config" }
codegen = { path = "../codegen" }
pctx_executor = { path = "../pctx_executor" }
pctx_code_execution_runtime = { path = "../pctx_code_execution_runtime" }
pctx_session_types = { path = "../pctx_session_types" }
pctx_websocket_server = { path = "../pctx_websocket_server" }

# general
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
schemars = "1.1.0"
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serial_test = "3"
